//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BillingSystem.DataModel
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class billingEntities1 : DbContext
    {
        public billingEntities1()
            : base("name=billingEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<calls> calls { get; set; }
        public DbSet<charge> charge { get; set; }
        public DbSet<payment> payment { get; set; }
        public DbSet<phone_number> phone_number { get; set; }
        public DbSet<position> position { get; set; }
        public DbSet<price> price { get; set; }
        public DbSet<service> service { get; set; }
        public DbSet<staff> staff { get; set; }
        public DbSet<subscriber> subscriber { get; set; }
        public DbSet<tariff> tariff { get; set; }
        public DbSet<tariff_history> tariff_history { get; set; }
    }
}
