//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BillingSystem.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class price
    {
        public long tariff_id { get; set; }
        public string prefix { get; set; }
        public float cost { get; set; }
    }
}
