//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BillingSystem.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tariff_history
    {
        public long id { get; set; }
        public long phone_id { get; set; }
        public long tariff_id { get; set; }
        public System.DateTime start_date { get; set; }
        public Nullable<System.DateTime> end_date { get; set; }
    }
}
