//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BillingSystem.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tariff
    {
        public long id { get; set; }
        public string name { get; set; }
        public string description { get; set; }
        public Nullable<float> debt_threshold { get; set; }
        public bool active { get; set; }
    }
}
